kind: pipeline
name: default

steps:
- name: node
  image: guoxudongdocker/node-drone
  commands:
  - rm -rf ./dist/static/ && rm -rf ./dist/index.html && rm -rf ./dist/serverconfig.json
  - npm install
  - npm run build

- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: hub.dh.com/zhzm/web
    registry: hub.dh.com
    tags: ${DRONE_BUILD_NUMBER}
    context: ./dist
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: daemon
    path: /etc/docker/certs.d/hub.dh.com


volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: daemon
  host:
    path: /etc/docker/certs.d/hub.dh.com
- name: mvncache
  host:
    path: /var/lib/mvn
trigger:
  branch:
  - master
  event:
  - push

