kind: pipeline
name: default

steps:
- name: node
  image: guoxudongdocker/node-drone
  commands:
  - rm -rf static/ && rm -rf index.html && rm -rf serverconfig.json
  - npm install
  - npm run build

- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: hub.dh.com/zhzm/web
    registry: hub.dh.com
    tags: ${DRONE_BUILD_NUMBER}
    context: ./dist
